"""App-mode (fallback) hosted checkout page.

When Stripe / Flutterwave credentials are missing or broken, checkout
sessions are issued with the ``app`` provider and their ``checkout_url``
points here. The page is intentionally unauthenticated — possession of
the one-time reference in the URL is the only credential. This matches
how external providers' hosted checkout URLs behave.

Two endpoints:
- GET  /payments/app-checkout/{reference}           — HTML simulator page
- POST /payments/app-checkout/{reference}/complete  — success / failure webhook

Both are public. Mount this router WITHOUT the ``/v1`` prefix so the URLs
match the ones generated by ``AppCheckoutPaymentProvider``.
"""

from __future__ import annotations

import html

from fastapi import APIRouter, HTTPException, Request, status
from fastapi.responses import HTMLResponse, JSONResponse

from repositories.checkout_repo import get_checkout_by_reference
from schemas.checkout_schema import CheckoutCompleteRequest, CheckoutStatus
from services.checkout_service import complete_checkout

router = APIRouter(prefix="/payments/app-checkout", tags=["App Payment Simulator"])


def _format_amount(amount_minor: int, currency: str) -> str:
    major = amount_minor / 100
    return f"{currency.upper()} {major:,.2f}"


def _render_page(
    *,
    reference: str,
    session_id: str,
    plan_display: str,
    amount: str,
    base_price: str,
    percent_off: float,
    fixed_off: str,
    discount_ids: list,
    status_label: str,
    completed: bool,
    failure_reason: str | None,
) -> str:
    completed_banner = ""
    action_block = ""
    if completed:
        status_class = (
            "bg-emerald-500" if status_label == "succeeded" else "bg-rose-500"
        )
        completed_banner = f"""
        <div class="mt-4 rounded-md {status_class} px-4 py-3 text-white text-sm font-medium">
          This checkout is <span class="uppercase tracking-wide">{html.escape(status_label)}</span>.
          {"You can close this window." if status_label == "succeeded" else ""}
          {f"<div class='opacity-80 text-xs mt-1'>{html.escape(failure_reason or '')}</div>" if failure_reason else ""}
        </div>
        """
    else:
        action_block = """
        <div class="mt-6 grid grid-cols-2 gap-3">
          <button id="success-btn"
            class="rounded-md bg-emerald-600 hover:bg-emerald-700 text-white font-semibold py-3 transition">
            Mark as paid
          </button>
          <button id="failure-btn"
            class="rounded-md bg-rose-600 hover:bg-rose-700 text-white font-semibold py-3 transition">
            Mark as failed
          </button>
        </div>
        <p class="mt-4 text-xs text-slate-500">
          App test mode. No real charge will be processed. This page only exists
          because no external payment provider is configured — the same flow will
          run against Stripe or Flutterwave once their keys are set.
        </p>
        """

    discount_row = ""
    if percent_off > 0 or fixed_off != "0.00":
        discount_row = f"""
        <div class="flex justify-between text-sm text-slate-600">
          <span>Discounts applied ({len(discount_ids)})</span>
          <span>-{percent_off:.1f}% / -{html.escape(fixed_off)}</span>
        </div>"""

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>VisiChek checkout (app mode)</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-slate-100 flex items-center justify-center p-4">
  <div class="w-full max-w-md bg-white rounded-2xl shadow-xl p-8">
    <div class="flex items-center gap-2 mb-6">
      <div class="h-2 w-2 rounded-full bg-amber-500"></div>
      <span class="text-xs font-semibold uppercase tracking-wider text-amber-700">
        App test mode
      </span>
    </div>
    <h1 class="text-xl font-semibold text-slate-900">{html.escape(plan_display)}</h1>
    <p class="text-slate-500 text-sm mt-1">Reference: <span class="font-mono">{html.escape(reference)}</span></p>

    <div class="mt-6 space-y-2">
      <div class="flex justify-between text-sm text-slate-700">
        <span>Base price</span>
        <span class="font-medium">{html.escape(base_price)}</span>
      </div>
      {discount_row}
      <div class="border-t border-slate-200 pt-2 mt-2 flex justify-between">
        <span class="text-slate-900 font-semibold">Total due</span>
        <span class="text-slate-900 font-semibold">{html.escape(amount)}</span>
      </div>
    </div>

    {completed_banner}
    {action_block}
  </div>

<script>
const ref = {reference!r};
async function complete(outcome) {{
  const btns = document.querySelectorAll('button');
  btns.forEach(b => b.setAttribute('disabled', 'true'));
  const res = await fetch(`/payments/app-checkout/${{ref}}/complete`, {{
    method: 'POST',
    headers: {{ 'Content-Type': 'application/json' }},
    body: JSON.stringify({{ outcome }}),
  }});
  if (res.ok) {{
    window.location.reload();
  }} else {{
    const body = await res.text();
    alert('Failed to complete: ' + body);
    btns.forEach(b => b.removeAttribute('disabled'));
  }}
}}
const okBtn = document.getElementById('success-btn');
const failBtn = document.getElementById('failure-btn');
if (okBtn) okBtn.addEventListener('click', () => complete('success'));
if (failBtn) failBtn.addEventListener('click', () => complete('failure'));
</script>
</body>
</html>"""


@router.get("/{reference}", include_in_schema=False)
async def render_app_checkout_page(reference: str, request: Request) -> HTMLResponse:
    session = await get_checkout_by_reference(reference)
    if not session:
        # Addon-purchase fallback page — same simulator, different copy.
        if reference.startswith("addon_"):
            from repositories.tenant_addon_repo import (
                get_tenant_addon_by_reference,
            )

            row = await get_tenant_addon_by_reference(reference)
            if row is None:
                raise HTTPException(status_code=404, detail="Addon purchase not found")
            amount = row.unit_price_snapshot * row.quantity
            completed = row.status.value != "pending"
            html_body = _render_page(
                reference=reference,
                session_id=row.id or "",
                plan_display=(f"Addon: {row.addon_kind.value} x{row.quantity}"),
                amount=f"{row.currency_snapshot.upper()} {amount:,.2f}",
                base_price=f"{row.currency_snapshot.upper()} {amount:,.2f}",
                percent_off=0.0,
                fixed_off="0.00",
                discount_ids=[],
                status_label=row.status.value,
                completed=completed,
                failure_reason=row.cancellation_reason,
            )
            return HTMLResponse(content=html_body, status_code=200)
        raise HTTPException(status_code=404, detail="Checkout session not found")

    plan_display = (session.metadata or {}).get(
        "plan_display_name"
    ) or f"Plan {session.plan_id[-6:]}"
    completed = session.status != CheckoutStatus.PENDING

    html_body = _render_page(
        reference=reference,
        session_id=session.id or "",
        plan_display=f"{plan_display} — {session.billing_cycle.value}",
        amount=_format_amount(session.amount_minor, session.currency),
        base_price=_format_amount(
            int(round(session.breakdown.base_price * 100)), session.currency
        ),
        percent_off=session.breakdown.total_percentage_off,
        fixed_off=f"{session.breakdown.total_fixed_off:,.2f}",
        discount_ids=session.breakdown.applied_discount_ids,
        status_label=session.status.value,
        completed=completed,
        failure_reason=session.failure_reason,
    )
    return HTMLResponse(content=html_body, status_code=200)


@router.post("/{reference}/complete", include_in_schema=False)
async def complete_app_checkout(
    reference: str, payload: CheckoutCompleteRequest
) -> JSONResponse:
    session = await get_checkout_by_reference(reference)
    if session and session.id is not None:
        result = await complete_checkout(
            checkout_id=session.id,
            outcome=payload.outcome,
        )
        return JSONResponse(
            status_code=status.HTTP_200_OK,
            content={
                "success": True,
                "status": result.status.value,
                "subscription_id": result.subscription_id,
                "reference": reference,
            },
        )

    # Addon-purchase fallback. Addon references are prefixed
    # ``addon_`` and don't live in the ``checkouts`` collection.
    if reference.startswith("addon_"):
        from repositories.tenant_addon_repo import (
            get_tenant_addon_by_reference,
        )
        from services.addon_service import (
            activate_tenant_addon_by_reference,
            cancel_tenant_addon,
        )

        row = await get_tenant_addon_by_reference(reference)
        if row is None or row.id is None:
            raise HTTPException(status_code=404, detail="Addon purchase not found")
        if payload.outcome == "success":
            activated = await activate_tenant_addon_by_reference(
                payment_reference=reference
            )
            status_value = activated.status.value if activated else "active"
        else:
            cancelled = await cancel_tenant_addon(
                row.id,
                actor_id=row.created_by_user_id or "system",
                reason=f"app-checkout {payload.outcome}",
            )
            status_value = cancelled.status.value
        return JSONResponse(
            status_code=status.HTTP_200_OK,
            content={
                "success": True,
                "status": status_value,
                "tenant_addon_id": row.id,
                "reference": reference,
            },
        )

    raise HTTPException(status_code=404, detail="Checkout session not found")
